### PR TITLE
Add aspect-ratio support

### PR DESCRIPTION
**Pull request by pearofducks**
This does add a bit of space to the core file, but seems to be used often enough in FINN it should be supported

### CODE REVIEW

**Review by digitalsadhu — COMMENTED** [review]
Would we want to restrict which aspect ratios are supported at all?

**Comment by pearofducks** [comment]
With this approach we kinda can't. It just adds X and Y rules, so the user can cook their own AR.

e.g.

```
aspect-w-16 aspect-h-9
```

So it's pretty difficult to eliminate any single number from the support. 🤷

**Comment by digitalsadhu** [comment]
Right yea, you can only filter to/out specific numbers not really combos. I suppose if you only allowed ratios it might work, or maybe it wouldn't. Wasn't clear to me from the docs. Probs not a big size increase?

**Comment by pearofducks** [comment]
Before

```
30.5 kB: fabric.min.css.br
460.81 kB: fabric.min.css.min.css
```

After:

```
31.1 kB: fabric.min.css.br
468.06 kB: fabric.min.css.min.css
```

**Comment by pearofducks** [comment]
Pretty sizeable hit, so I'm OK if we wanna support this another way - but does seem to be used enough it might be worth just eating it?

**Comment by digitalsadhu** [comment]
Yea, we could end up dying from a thousand paper cuts as we add features back in 😆 
I don't have much to add regarding whether its worth it or not in this case. I've asked all my questions 🤣 🚀

**Pull request merged**
